### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by ange-diambote** [cuba-platform/frontend#275]
Hi, i need to add french in template. There is a way to add it?

**Comment by vyacheslav-pushkin** [comment]
Hi @ange-diambote,

Yes, please refer to [this guide](https://doc.cuba-platform.com/frontend/cuba-frontend-docs/v20.1/client-react/i18n.html#_adding_support_for_new_locales).

**Comment by ange-diambote** [comment]
It work fine with a already generated project, I need to a local in the generator and template. I found there is many place where rule for ‘ru’ and ‘en’ are hardcoded in the generator.

**Comment by ange-diambote** [comment]
I want to add French translation in master and share it with all the community, so every one will have has available local like ‘ru’

**Comment by vyacheslav-pushkin** [comment]
Sounds awesome!

Like you said, there is currently a bunch of places where you need to make changes in order to add a new locale. We are going to make this process more simple and straightforward (#276). For now I can suggest the following:

- You can make a PR with translated messages only and we will handle the rest. The messages that needs to be translated are:
  - `packages/front-generator/src/generators/react-typescript/app/template/i18n-message-packs/en.json`
  - `packages/front-generator/src/generators/react-typescript/entity-management/entity-management-en.json`
- Alternatively we can prepare a doc explaining what changes needs to be made, so that you can make a full PR.

I think it's probably best to go with option 1. Please let me know which option do you prefer.

**Comment by ange-diambote** [comment]
Like you said adding new local is complex. I have modified i18n.test.ts, i18nMappings.ts.ejs, entity-management/index.ts and others but with not success. I have already create fr.json file so I choose option 1

**Comment by vyacheslav-pushkin** [comment]
Hi @ange-diambote,

Thanks again for your contribution! I've made the necessary changes, PR #279 is currently going through a peer review.

I've added a key: 

```
"common.retry": "Recommencer"
```

Does it sound correct to you?

**Comment by ange-diambote** [comment]
You re welcome, Yes it does.
Is there a technical document for the generator, it can help be to understand how is made and I can contribute with code.
